[[중고글-작성]]
=== 중고글 작성
operation::product-post-write[snippets='http-request,request-headers,request-fields,http-response,response-fields']

[[중고글-조회]]
=== 중고글 조회
operation::product-post-get[snippets='http-request,request-headers,path-parameters,http-response,response-fields']

[[중고글-목록-조회]]
=== 중고글 목록 조회
operation::product-post-list[snippets='http-request,request-parameters,http-response,response-fields']

[[중고글-카테고리-조회]]
=== 중고글 목록 카테고리별 조회
operation::product-post-list-category[snippets='http-request,path-parameters,http-response,response-fields']

[[내-중고글-목록-조회]]
=== 내 중고글 목록 조회
operation::product-post-list-my[snippets='http-request,request-headers,request-parameters,http-response,response-fields']

[[내-중고글-조회]]
=== 내 중고글 조회
operation::product-post-my-post[snippets='http-request,http-response,response-fields']

[[내-중고글-수정]]
=== 내 중고글 수정
operation::product-post-my-post-edit[snippets='http-request,request-headers,http-response,response-fields']

[[내-중고글-삭제]]
=== 내 중고글 삭제
operation::product-post-my-post-delete[snippets='http-request,request-headers,http-response,response-fields']

[[중고글-목록-검색]]
=== 중고글 검색
operation::product-post-list-search[snippets='http-request,request-parameters,http-response,response-fields']
